In [24]:
## Import libraries

import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import regex as re
from sklearn.preprocessing import normalize
from sklearn.feature_selection import VarianceThreshold

In [25]:
'''
Function: outcome_split

Purpose: Make the outcome variable binary, splitting it  within the percentiles
of previously inputed low and high tails. 

Input: Dataframe, outcome variable name, low tail value, high tail value

Output: Dataframe with "outcome" variable split in 1s and 0s as asked by the user

'''

def outcome_split(df, outcome, low_tail, high_tail):
    
    ## Create percentiles

    my_series = df[outcome]
    my_series = my_series.values.tolist()
    my_series = np.array(my_series)

    q1, q3 = np.percentile(my_series, [low_tail, high_tail])
    
    print(q1)
    print(q3)
    
    ## Divide by percentiles

    constraint = df[outcome] >= q3
    constraint2 = df[outcome] < q1


    df.loc[constraint, 'outcome'] = int(1)
    df.loc[constraint2, 'outcome'] = int(0)
    
    df.dropna(subset = ['outcome'], inplace=True)
    
    return df

In [26]:
'''
Function: clean_data

Purpose: Transform yes and no into 1 and 0, remove some useless variables, drop variables 
less that 220 entries, only keep numerical variables

Input: Dataframe with the data

Output: Clean dataframe

'''

def clean_data(df):
    
    # Replace yes or no answers for 1 and 0
    df = df.replace("sim", int(1))
    df = df.replace("Sim", int(1))
    df = df.replace("SIM", int(1))
    df = df.replace("s", int(1))
    df = df.replace("S", int(1))
    df = df.replace("yes", int(1))
    df = df.replace("Yes", int(1))
    df = df.replace("YES", int(1))
    df = df.replace("y", int(1))
    df = df.replace("Y", int(1))
    df = df.replace("nao", int(0))
    df = df.replace("Nao", int(0))
    df = df.replace("NAO", int(0))
    df = df.replace("não", int(0))
    df = df.replace("Não", int(0))
    df = df.replace("NÃO", int(0))
    df = df.replace("n", int(0))
    df = df.replace("N", int(0))
    df = df.replace("No", int(0))
    df = df.replace("no", int(0))
    df = df.replace("NO", int(0))
    
    r = re.compile(".*bks*")
    id_columns = list(filter(r.match, df.columns)) # Read Note
    df.drop(columns=id_columns, inplace=True)
    
    r = re.compile("ID_.*")
    id_columns = list(filter(r.match, df.columns)) # Read Note
    df.drop(columns=id_columns, inplace=True)
    
    r = re.compile("TMRAW.*")
    id_columns = list(filter(r.match, df.columns)) # Read Note
    df.drop(columns=id_columns, inplace=True)
    
    r = re.compile("RESP.*")
    id_columns = list(filter(r.match, df.columns)) # Read Note
    df.drop(columns=id_columns, inplace=True)
    
    r = re.compile("G05")
    id_columns = list(filter(r.match, df.columns)) # Read Note
    df.drop(columns=id_columns, inplace=True)
    
    
    df = df.apply(pd.to_numeric, errors='ignore')
    df = df.select_dtypes(include=np.number)
    
    
    
    df.dropna(thresh=220, axis=1, inplace=True)
    
    for var in df.columns:
        if df[var].nunique() == 1:
            df.drop(columns=[var], inplace=True)
    
    print("\nThe clean dataset has", df.shape[0], "rows and", df.shape[1], "columns")
    
    return df

In [27]:
'''
Function: feature_variance_finder

Purpose: Removing variables below a variance threshold

Input: Dataframe with the data and desired variance threshold

Output: Dataframe without the low variance features

'''


def feature_variance_finder(data, thresh):
   
    normalized = normalize(data)
    data_scaled = pd.DataFrame(normalized)
    
    data_scaled.var()
    
    #storing the variance and name of variables
    variance = data_scaled.var()
    columns = data.columns
    
    #saving the names of variables having variance more than a threshold value

    variable = [ ]

    for i in range(0,len(variance)):
        if variance[i]>=thresh: #setting the threshold as 1%
            variable.append(columns[i])
            
    new_data = data[variable]
    
    return new_data

In [28]:
## Open the excel file
name= "../data/Data_filtered_PROPER.csv"
df = pd.read_csv(name)

In [29]:
## Split outcome 70/30 and drop any possible missing data
df_70_30 = outcome_split(df, "CSSA5.TOTAL", 30, 70)

df_70_30.dropna(inplace=True, axis=1)

df_70_30.dropna(inplace=True)

18.0
39.0

In [8]:
## Check shape of resulting dataframe
df_70_30.shape

(240, 277)

In [9]:
## Drop uninformative columns and columns that contain direct information about outcome
df_70_30.drop(columns=["Unnamed: 0", "ID_continua.int", "CSSAimprove", "CSSA5.TOTAL"], inplace=True)

In [10]:
## Clean data converting all remaining variables into numerical values and dropping any that cannot be converted
df_70_30 = clean_data(df_70_30)

The clean dataset has 240 rows and 261 columns

In [11]:
## Remove features with low variance
df_70_30 = feature_variance_finder(df_70_30, 0.0000001)

In [12]:
## Clean data converting all remaining variables into numerical values and dropping any that cannot be converted
df_70_30 = clean_data(df_70_30)

The clean dataset has 240 rows and 228 columns

In [14]:
for col in df_70_30.columns:
    print(col, df_70_30[col].value_counts())

T_S1 50    27
52    26
53    21
54    21
55    20
51    16
48    15
59    14
58    12
57    12
49    12
47     9
46     6
56     5
45     5
62     4
42     4
60     3
44     3
43     1
72     1
66     1
63     1
40     1
Name: T_S1, dtype: int64
T_S2 48    131
70     20
66     17
60     12
69     10
72      7
64      7
79      7
67      5
63      4
62      4
61      4
59      4
76      3
75      2
74      1
71      1
65      1
Name: T_S2, dtype: int64
T_S3 56    94
38    67
47    15
55    12
50     9
43     8
52     7
51     7
45     6
44     5
53     4
49     4
54     2
Name: T_S3, dtype: int64
T_S4 53    24
52    16
45    15
50    15
46    14
49    13
43    12
51    11
55    10
31    10
47     9
42     9
54     8
57     8
44     7
58     7
48     7
37     6
35     5
36     5
56     5
41     4
39     4
60     4
61     3
38     2
59     2
63     1
65     1
40     1
66     1
67     1
Name: T_S4, dtype: int64
T_S5 37    22
48    19
41    15
49    14
57    13
46    13
39    12
63    11
60    11
42    10
55    10
53    10
52     9
43     9
45     9
44     8
29     8
50     8
65     8
59     7
68     3
34     3
66     2
71     2
73     1
61     1
70     1
75     1
Name: T_S5, dtype: int64
T_S6 46    117
56     79
57      9
59      7
65      5
62      5
63      4
58      4
67      3
60      3
64      2
72      1
61      1
Name: T_S6, dtype: int64
T_S7 42    103
40     57
38     28
36     20
39     15
33      5
43      3
53      2
37      2
31      2
28      2
35      1
Name: T_S7, dtype: int64
T_S8 73    193
27     15
51     11
41     11
62     10
Name: T_S8, dtype: int64
T_S9 78    63
74    29
36    24
55    23
46    15
64    10
48     7
53     6
44     6
51     6
72     6
70     6
60     5
71     5
63     5
40     5
62     3
66     3
42     3
73     2
50     2
57     2
54     1
52     1
65     1
69     1
Name: T_S9, dtype: int64
G15 37.0    14
33.0    13
26.0    12
35.0    11
30.0    11
18.0    11
25.0    10
27.0    10
36.0     9
40.0     9
38.0     8
34.0     8
29.0     8
28.0     8
31.0     8
41.0     7
46.0     7
22.0     7
42.0     6
20.0     6
19.0     6
24.0     5
21.0     5
39.0     5
23.0     4
52.0     4
32.0     4
49.0     3
43.0     3
45.0     3
44.0     3
56.0     2
51.0     2
47.0     2
53.0     2
17.0     2
57.0     1
48.0     1
Name: G15, dtype: int64
H1_A 0      59
6      17
7      14
10     11
11      9
20      8
15      8
1       8
8       8
4       7
12      7
2       7
13      5
5       5
26      5
21      4
27      4
3       4
9       3
16      3
17      3
18      3
180     3
36      3
48      3
32      3
60      3
31      2
14      2
34      2
22      2
150     1
99      1
97      1
80      1
68      1
62      1
159     1
47      1
45      1
35      1
30      1
28      1
25      1
24      1
23      1
Name: H1_A, dtype: int64
H2_A 0      67
6      18
7      16
10     14
1      11
3       9
11      9
2       8
15      8
8       8
4       7
12      7
9       6
17      5
5       5
20      5
13      4
27      3
14      3
16      2
18      2
30      2
24      2
26      2
28      2
21      2
34      2
36      1
80      1
72      1
68      1
48      1
97      1
32      1
25      1
23      1
22      1
150     1
Name: H2_A, dtype: int64
H3_A 0     206
2       8
1       6
15      3
7       3
60      2
21      2
3       2
97      1
30      1
14      1
12      1
11      1
8       1
6       1
4       1
Name: H3_A, dtype: int64
H4_A 0     232
80      1
30      1
21      1
15      1
14      1
6       1
3       1
1       1
Name: H4_A, dtype: int64
H5_A 0      233
1        2
177      1
30       1
17       1
14       1
7        1
Name: H5_A, dtype: int64
H6_A 0      228
7        2
150      1
140      1
90       1
45       1
30       1
17       1
14       1
3        1
2        1
1        1
Name: H6_A, dtype: int64
H7_A 0     236
4       2
69      1
12      1
Name: H7_A, dtype: int64
H8_A 0     231
30      3
4       2
90      1
60      1
18      1
2       1
Name: H8_A, dtype: int64
H9_A 0      188
7        8
3        5
1        4
60       3
2        3
5        3
30       3
180      3
90       3
120      3
25       2
20       2
15       2
65       1
170      1
13       1
84       1
4        1
156      1
169      1
21       1
Name: H9_A, dtype: int64
H10 0    222
1     18
Name: H10, dtype: int64
H11_1 0    207
1     33
Name: H11_1, dtype: int64
H11_2 0    164
1     76
Name: H11_2, dtype: int64
H11_3 0    157
1     83
Name: H11_3, dtype: int64
H11_4 0    180
1     60
Name: H11_4, dtype: int64
H11_5 0    192
1     48
Name: H11_5, dtype: int64
H11_6 0    220
1     20
Name: H11_6, dtype: int64
H11_8 0    221
1     19
Name: H11_8, dtype: int64
H12 0    171
1     69
Name: H12, dtype: int64
H13_A 0      52
6      17
7      15
10     11
1      10
11     10
15      9
2       8
8       8
4       7
12      7
20      7
3       6
21      5
13      5
26      4
27      4
17      3
18      3
48      3
16      3
36      3
9       3
5       3
14      2
23      2
22      2
180     2
30      2
32      2
34      2
90      2
24      1
72      1
160     1
159     1
150     1
99      1
80      1
77      1
65      1
68      1
174     1
60      1
47      1
42      1
35      1
31      1
28      1
25      1
Name: H13_A, dtype: int64
M3 0    212
1     28
Name: M3, dtype: int64
M4 0    229
1     11
Name: M4, dtype: int64
M6 0    237
1      3
Name: M6, dtype: int64
M7 0    225
1     15
Name: M7, dtype: int64
M9_Composite 0    201
1     39
Name: M9_Composite, dtype: int64
M10 0    230
1     10
Name: M10, dtype: int64
M11 0    218
1     22
Name: M11, dtype: int64
M13 0    231
1      9
Name: M13, dtype: int64
M14 0    151
1     89
Name: M14, dtype: int64
M15 0    186
1     54
Name: M15, dtype: int64
M3to15_NumbChronicDisease 1    81
0    81
2    44
3    21
4    10
7     1
6     1
5     1
Name: M3to15_NumbChronicDisease, dtype: int64
M16 0    197
1     43
Name: M16, dtype: int64
M20 0     123
30     29
7      17
3      12
15      8
4       8
2       8
1       7
10      6
5       6
20      4
25      4
14      3
21      2
12      1
6       1
8       1
Name: M20, dtype: int64
M21 0     168
2      12
1       9
30      8
3       7
7       6
4       6
5       5
15      4
14      4
10      4
20      2
9       2
28      1
25      1
21      1
Name: M21, dtype: int64
M25 0      96
1      48
2      27
3      23
4      13
5       7
20      4
6       3
10      3
12      2
11      2
25      2
90      1
9       1
8       1
7       1
14      1
15      1
17      1
40      1
44      1
120     1
Name: M25, dtype: int64
M26_A 0     168
1      28
2      20
3       9
4       5
15      4
10      2
6       2
7       1
5       1
Name: M26_A, dtype: int64
M27_A 0      158
180     18
7       13
10       8
2        4
3        4
60       4
30       4
14       4
15       2
1        2
4        2
150      2
12       1
5        1
6        1
8        1
173      1
175      1
33       1
40       1
46       1
59       1
90       1
95       1
115      1
120      1
21       1
Name: M27_A, dtype: int64
M28_A 0      158
1       35
2       12
3        9
6        7
10       5
24       2
20       2
5        2
4        2
180      1
18       1
15       1
11       1
9        1
7        1
Name: M28_A, dtype: int64
E9 1    206
0     34
Name: E9, dtype: int64
E19 0     177
20      8
2       6
1       5
15      5
10      4
6       4
8       3
25      3
24      3
23      3
16      3
3       2
4       2
27      2
21      2
22      2
12      2
7       1
9       1
26      1
13      1
Name: E19, dtype: int64
E20_adj 0      51
200    12
500     8
150     7
300     5
       ..
176     1
945     1
180     1
160     1
391     1
Name: E20_adj, Length: 113, dtype: int64
E21 0     223
1       8
5       3
2       2
20      1
16      1
14      1
7       1
Name: E21, dtype: int64
E24 0    223
1     17
Name: E24, dtype: int64
E29_B_adj 0        129
300        6
500        6
1800       6
1200       5
        ...
24000      1
120        1
6000       1
2800       1
5000       1
Name: E29_B_adj, Length: 63, dtype: int64
E31_1 0    212
1     28
Name: E31_1, dtype: int64
E31_3 0    222
1     18
Name: E31_3, dtype: int64
E31_5 0    200
1     40
Name: E31_5, dtype: int64
E31_6 0    232
1      8
Name: E31_6, dtype: int64
E31_7 0    158
1     82
Name: E31_7, dtype: int64
E31_11 0    163
1     77
Name: E31_11, dtype: int64
E32 0    225
1     15
Name: E32, dtype: int64
E33 0    171
1     69
Name: E33, dtype: int64
E34 0    132
1    108
Name: E34, dtype: int64
E36 0    174
1     66
Name: E36, dtype: int64
D01 1     58
2     48
3     24
5     23
0     21
4     19
6     15
7      7
8      5
10     5
15     3
9      2
11     2
12     2
25     1
13     1
14     1
16     1
20     1
34     1
Name: D01, dtype: int64
D02 1     74
2     48
3     24
0     23
5     20
4     16
6      9
7      7
10     5
8      3
12     3
9      2
25     1
14     1
15     1
16     1
23     1
29     1
Name: D02, dtype: int64
D04A 0      151
2       11
6        9
1        8
12       7
3        4
24       3
4        3
5        3
10       3
20       3
180      3
30       3
16       2
8        2
52       2
14       2
48       2
11       2
7        2
9        2
100      1
75       1
72       1
60       1
27       1
21       1
13       1
15       1
150      1
17       1
18       1
28       1
40       1
Name: D04A, dtype: int64
D05A 0      111
180     34
10       7
8        7
30       5
120      5
7        5
60       4
6        4
15       4
90       3
5        3
4        3
9        3
2        3
11       3
1        3
150      3
14       3
72       2
12       2
20       2
17       1
3        1
13       1
156      1
21       1
18       1
19       1
165      1
28       1
32       1
36       1
37       1
55       1
64       1
88       1
91       1
92       1
99       1
115      1
143      1
24       1
Name: D05A, dtype: int64
D06A 0      199
24       6
1        6
2        6
180      3
48       2
32       2
15       2
8        2
4        2
30       1
64       1
22       1
120      1
18       1
12       1
5        1
72       1
100      1
21       1
Name: D06A, dtype: int64
D07_Yrs 0.000000e+00    204
8.333333e-02      8
1.666667e-01      5
3.333333e-01      4
1.000000e+00      3
5.000000e-01      3
2.500000e-01      3
4.000000e+00      2
9.166667e-01      1
2.416667e+14      1
1.083333e+14      1
1.916667e+14      1
6.666667e-01      1
2.000000e+00      1
3.000000e+00      1
1.000000e+01      1
Name: D07_Yrs, dtype: int64
D08 0     118
2      23
5      11
1      10
15      8
4       7
3       7
10      7
12      6
21      3
20      3
25      3
13      3
28      3
11      3
26      3
8       3
18      2
14      2
9       2
7       2
6       2
35      1
32      1
30      1
29      1
40      1
16      1
17      1
23      1
41      1
Name: D08, dtype: int64
D09 0     126
2      24
5      14
1      11
15      6
4       6
3       5
10      5
12      5
20      4
8       3
13      3
21      3
26      3
28      3
14      2
35      2
11      2
7       2
6       2
25      2
16      1
17      1
18      1
9       1
29      1
30      1
41      1
Name: D09, dtype: int64
D10 1    145
0     95
Name: D10, dtype: int64
D13 0     91
30    20
1     17
4     11
10    11
3     11
20     8
2      8
15     7
6      5
8      5
9      5
14     5
22     4
23     4
7      4
5      4
18     3
26     3
12     3
21     3
24     3
27     1
28     1
19     1
25     1
13     1
Name: D13, dtype: int64
D15 0     112
1      16
30     15
2      11
4       8
3       7
10      6
9       6
22      5
6       5
20      5
14      4
23      4
15      4
8       4
7       3
25      3
24      3
12      3
19      3
5       3
26      2
13      2
18      2
21      2
28      1
11      1
Name: D15, dtype: int64
D16 0       138
100      14
50        8
10        6
20        6
150       5
15        5
30        5
40        5
200       5
300       4
60        3
5         2
1000      2
1500      2
500       2
600       2
350       2
400       2
650       1
2         1
3         1
4         1
450       1
264       1
700       1
270       1
16        1
18        1
84        1
80        1
28        1
130       1
288       1
360       1
42        1
484       1
45        1
70        1
75        1
27        1
Name: D16, dtype: int64
D17 0    195
1     45
Name: D17, dtype: int64
D18 0    162
1     78
Name: D18, dtype: int64
D19 0    157
1     83
Name: D19, dtype: int64
D20 0    178
1     62
Name: D20, dtype: int64
D21 0     154
30     15
2      12
20      9
7       9
3       8
1       7
15      6
4       4
5       2
10      2
14      2
9       1
8       1
17      1
6       1
18      1
21      1
22      1
25      1
28      1
31      1
Name: D21, dtype: int64
D25 1    222
0     18
Name: D25, dtype: int64
D25C 1    163
0     77
Name: D25C, dtype: int64
D26 0    173
1     67
Name: D26, dtype: int64
D26C 0    200
1     40
Name: D26C, dtype: int64
D27 1    220
0     20
Name: D27, dtype: int64
D27C 1    170
0     70
Name: D27C, dtype: int64
D27B_CocaineRegAbuseRatio 0.000000    90
0.100000     5
0.200000     4
0.166667     4
0.222222     4
            ..
0.259259     1
0.078947     1
0.075000     1
0.147059     1
0.444444     1
Name: D27B_CocaineRegAbuseRatio, Length: 109, dtype: int64
D28 1    201
0     39
Name: D28, dtype: int64
D28C 1    177
0     63
Name: D28C, dtype: int64
D28B_CrackRegAbuseRatio 0.000000    87
0.142857     5
0.111111     5
0.347826     4
0.200000     4
            ..
0.208333     1
0.057692     1
0.367347     1
0.346154     1
0.478261     1
Name: D28B_CrackRegAbuseRatio, Length: 107, dtype: int64
D2728B 0.0     31
1.0     22
4.0     19
8.0     19
2.0     19
5.0     17
7.0     14
10.0    13
11.0    13
12.0    13
6.0     12
3.0     12
9.0     11
15.0     5
16.0     5
14.0     4
13.0     4
17.0     3
18.0     2
19.0     1
20.0     1
Name: D2728B, dtype: int64
D2728D 30.0    146
1.0      14
0.0       9
8.0       7
3.0       7
5.0       7
15.0      6
10.0      6
14.0      6
12.0      5
24.0      4
7.0       3
20.0      3
16.0      2
13.0      2
23.0      2
21.0      2
2.0       2
4.0       2
18.0      1
9.0       1
17.0      1
22.5      1
25.0      1
Name: D2728D, dtype: int64
D2728B_CrackCocaineRegAbuseRatio 0.000000    31
0.200000     7
0.111111     6
0.222222     6
0.347826     5
            ..
0.085106     1
0.419355     1
0.264706     1
0.064516     1
0.478261     1
Name: D2728B_CrackCocaineRegAbuseRatio, Length: 138, dtype: int64
D29 0    222
1     18
Name: D29, dtype: int64
D30 0    213
1     27
Name: D30, dtype: int64
D30C 0    236
1      4
Name: D30C, dtype: int64
D32 0    235
1      5
Name: D32, dtype: int64
D33 0    147
1     93
Name: D33, dtype: int64
D33C 0    202
1     38
Name: D33C, dtype: int64
D33Tabaco 1    223
0     17
Name: D33Tabaco, dtype: int64
D33TabacoB 0     159
10     12
6      10
12      9
11      9
9       9
8       9
7       7
4       4
2       3
13      2
5       2
3       2
18      1
17      1
1       1
Name: D33TabacoB, dtype: int64
D33TabacoC 1    210
0     30
Name: D33TabacoC, dtype: int64
D33TabacoD 30    191
0      26
15      4
10      4
14      2
8       2
3       2
31      1
24      1
22      1
21      1
20      1
18      1
16      1
12      1
2       1
Name: D33TabacoD, dtype: int64
D33TabacoG 10    82
0     69
1     40
8     10
5     10
9      9
7      7
4      6
2      3
6      2
3      2
Name: D33TabacoG, dtype: int64
D33TabacoB_NicotineRegAbuseRatio 0.000000    159
0.333333      6
0.461538      4
0.400000      3
0.285714      3
0.318182      2
0.444444      2
0.296296      2
0.270270      2
0.454545      2
0.360000      2
0.480000      2
0.423077      2
0.500000      2
0.222222      2
0.260870      1
0.363636      1
0.350000      1
0.312500      1
0.344828      1
0.481481      1
0.391304      1
0.230769      1
0.555556      1
0.289474      1
0.058824      1
0.370370      1
0.384615      1
0.375000      1
0.392857      1
0.464286      1
0.357143      1
0.097561      1
0.388889      1
0.142857      1
0.314286      1
0.083333      1
0.277778      1
0.239130      1
0.291667      1
0.458333      1
0.194444      1
0.380952      1
0.051282      1
0.514286      1
0.346154      1
0.523810      1
0.090909      1
0.450000      1
0.054054      1
0.157895      1
0.181818      1
0.485714      1
0.264706      1
0.315789      1
0.240000      1
0.135135      1
0.473684      1
0.210526      1
0.478261      1
Name: D33TabacoB_NicotineRegAbuseRatio, dtype: int64
D57 0     29
10    13
22    12
23    12
15    11
20    10
6     10
24    10
8      9
9      9
25     8
12     8
11     8
17     8
7      7
14     6
18     6
21     6
16     5
30     5
2      4
19     4
27     4
26     4
38     3
13     3
31     3
35     3
4      3
28     2
29     2
33     2
40     2
5      2
3      2
41     1
1      1
43     1
39     1
52     1
Name: D57, dtype: int64
D39 30    32
20    19
23    14
15    14
0     13
14    12
22    12
10    11
25     9
18     9
1      8
2      8
24     8
19     8
26     7
21     6
13     6
3      6
7      6
8      5
6      4
17     4
5      4
16     3
28     3
12     3
27     2
4      2
9      1
11     1
Name: D39, dtype: int64
D42 0    125
1    115
Name: D42, dtype: int64
D43 1    187
0     53
Name: D43, dtype: int64
D44 1    189
0     51
Name: D44, dtype: int64
D45 1    145
0     95
Name: D45, dtype: int64
D46 30    51
0     37
20    19
7     16
10    14
1     13
15    12
2     11
3     11
14     8
24     6
22     5
4      5
19     4
21     4
18     3
6      3
5      3
25     2
13     2
26     2
11     2
23     2
28     1
8      1
12     1
17     1
31     1
Name: D46, dtype: int64
D59 0    222
1     18
Name: D59, dtype: int64
D60 0     233
7       2
1       2
25      1
13      1
10      1
Name: D60, dtype: int64
L1 0    153
1     87
Name: L1, dtype: int64
L2 0    189
1     51
Name: L2, dtype: int64
L4 0    215
1      8
2      7
3      5
5      4
4      1
Name: L4, dtype: int64
L6 0     231
6       2
3       2
1       2
36      1
18      1
12      1
Name: L6, dtype: int64
L7_A 0     228
1      10
12      1
3       1
Name: L7_A, dtype: int64
L8_A 0     228
1      10
12      1
2       1
Name: L8_A, dtype: int64
L9_A 0    215
1     17
3      2
2      2
9      1
8      1
6      1
5      1
Name: L9_A, dtype: int64
L9_B 0    233
1      6
2      1
Name: L9_B, dtype: int64
L11_A 0    234
1      6
Name: L11_A, dtype: int64
L14_A 0     232
1       7
45      1
Name: L14_A, dtype: int64
L16 0    215
1     19
3      2
2      2
9      1
4      1
Name: L16, dtype: int64
L17_A 0    225
1      7
3      3
9      1
8      1
5      1
4      1
2      1
Name: L17_A, dtype: int64
L18 0    224
1     16
Name: L18, dtype: int64
L19 0    232
1      8
Name: L19, dtype: int64
L21 0    229
1     11
Name: L21, dtype: int64
L26_B 0     229
3       2
1       2
21      1
19      1
15      1
14      1
13      1
12      1
2       1
Name: L26_B, dtype: int64
L27_B 0     223
1      10
3       3
2       2
31      1
15      1
Name: L27_B, dtype: int64
L28_B 0     226
1       5
3       3
4       2
30      1
10      1
8       1
7       1
Name: L28_B, dtype: int64
L28_C 0     237
60      1
7       1
2       1
Name: L28_C, dtype: int64
L28_D 0     234
1       4
20      1
17      1
Name: L28_D, dtype: int64
L29_B 0     215
1      16
2       3
7       2
3       2
15      1
13      1
Name: L29_B, dtype: int64
L29_C 0      216
1        9
2        4
3        3
10       2
7        2
150      1
60       1
30       1
4        1
Name: L29_C, dtype: int64
L29_D 0    233
1      3
2      2
7      1
6      1
Name: L29_D, dtype: int64
L29_E 0      209
1       16
2        4
12       2
3        2
150      1
40       1
30       1
15       1
10       1
6        1
4        1
Name: L29_E, dtype: int64
L29_G 0    239
6      1
Name: L29_G, dtype: int64
L30_C 0      229
1        6
3        2
168      1
7        1
2        1
Name: L30_C, dtype: int64
L30_D 0      218
180      9
30       2
7        2
120      1
80       1
18       1
12       1
10       1
4        1
3        1
2        1
1        1
Name: L30_D, dtype: int64
L30_E 0    237
7      1
6      1
2      1
Name: L30_E, dtype: int64
L32_B 0     235
1       3
20      1
8       1
Name: L32_B, dtype: int64

In [18]:
## Split train and test dataset 80/20 split
train_70_30, test_70_30 = train_test_split(df_70_30, test_size=0.20, random_state=42)

In [19]:
## Check shape of train dataset
train_70_30.shape

(192, 228)

In [20]:
## Check shape of test dataset
test_70_30.shape

(48, 228)

In [21]:
## Save test and train dataset
train_70_30.to_csv("../data/train_70_30.csv", index=False)
test_70_30.to_csv("../data/test_70_30.csv", index=False)